services:
  - type: web
    name: chess-private-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 4 --timeout 120 server:app
    healthCheckPath: /
